export type cooperations = {
  partnerID: 3;
  cooperationID: 1;
  parentID: null;
  companyID: 1;
  userName: "m.athanasakis";
  passsword: "214Mar!@#";
  argoPaySpotID: null;
  recommendationSheet: "2021-01-27T00:00:00";
  partnerToSignDate: "2021-01-27T00:00:00";
  partnerSignedDate: "2021-02-05T00:00:00";
  contractSigned: "2021-02-05T00:00:00";
  requestCode: null;
  deliverZenithCodes: null;
  homeLowVoltageID: 65;
  airTimeLowVoltage: 7.0;
  renewalElectricity: 7;
  midlVoltage: 150;
  airTimeMidlVoltage: 0.2;
  homeAutoProGas: null;
  airTime1: null;
  airTime2: null;
  renewalGas: null;
  comments: "---";
  createdOn: "2022-03-19T13:12:49.31";
  createdBy: null;
  modifiedOn: "2022-03-19T13:12:49.31";
  modifiedBy: null;
};

export type parters = {
  cooperations: cooperations[];
  customers: [];
  partnerID: string;
  parentID: string;
  name: string;
  legalRepresentive: string;
  district: string;
  address: string;
  zip: string;
  ocupationID: string;
  vatID: string;
  phone1: string;
  phone2: string;
  mobile1: string;
  mobile2: string;
  email: string;
  contactName: string;
  infos: string;
  bankID: string;
  iban: string;
  createdOn: string;
  createdBy: string;
  modifiedOn: string;
  modifiedBy: string;
};
